runtime: go
api_version: go1
env: standard
threadsafe: false
instance_class: F1
handlers:
  - url: '/.*'
    script: _go_app
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic